const names = require('./names');
const sayHi = require('./utils');
require('./mind-grenade');
const data = require('./alternative-flavor');
// console.log(names);
// console.log(data);
// sayHi('Susan');
// sayHi(names.michael);
sayHi(names.nina);
// myName()howOld(names.nina);
